---
title: "Project 2"
author: "Damodar Pai"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes 
    toc_float: yes
---

# Introduction  

# Variables  

Data Labeling: 

CRIM: per capita crime rate by town (numeric)\n \n \n
ZN: proportion of residential land zoned for lots over 25,000 sq.ft. (numeric)\n
INDUS: proportion of non-retail business acres per town (numeric)
CHAS: Charles River dummy variable (1 if tract bounds river; 0 otherwise) (categorical)
NOX: nitric oxides concentration (parts per 10 million) (numeric)
RM: average number of rooms per dwelling (numeric)
AGE: proportion of owner-occupied units built prior to 1940 (numeric)
DIS: weighted distances to five Boston employment centres (numeric)
RAD: index of accessibility to radial highways (numeric)
TAX: full-value property-tax rate per $10,000 (numeric)
PTRATIO: pupil-teacher ratio by town (numeric)
B: 1000(Bk - 0.63)^2 where Bk is the proportion of [people of African American descent] by town (numeric)
LSTAT: % lower status of the population (numeric)
MEDV: Median value of owner-occupied homes in $1000s (target variable) (numeric)

# Research Question  

The Research Question I'm trying to answer is if there's a relationship between Age and the Median Value of a house within a particular town.  

```{r}

```



